### PR TITLE
Prevent over-sizing of group heatmaps in nested columns

### PR DESCRIPTION
**Pull request by thinkh**
closes Caleydo/lineup_app#46

**prerequisites**: 
 * [x] branch is up-to-date with the branch to be merged with, i.e. develop
 * [x] build is successful
 * [x] code is cleaned up and formatted 
 * [x] tested with Firefox 52, Firefox 57+, Chrome 64+, MS Edge 16+

### Summary

The over-sizing is caused by the increased row height for aggregated groups.

Reducing the row height to the standard `18px` will result in a normal heatmap width for nested columns.

image

As soon as I increase the height the width of the nested heatmaps increases exceeds the column.

image

By adding a `width:100%` the heatmaps stay within their column width.

image

However, now the gap between the nested columns disappeared. Hence, we must subtract the gap from the width to stay inline with the (nested column) grid.

image

### CODE REVIEW

**Comment by sgratzl** [comment]
doesn't work for me, in Chrome I get: 

image

i.e Sass is not translating this variable thus the whole rule is invalid and does nothing.

**Comment by sgratzl** [comment]
test file: https://github.com/lineupjs/lineupjs/blob/thinkh/nested-column-stack-renderer/demo/nested_bug_pr133.html

**Comment by thinkh** [comment]
Thanks for pointing out. It's fixed now. I needed to [escape the Sass variable](https://stackoverflow.com/a/20236515).

**Comment by sgratzl** [comment]
one thing that I didn't get. when you tested this PR with the buggy CSS selector and still the behavior wasn't there anymore. How can this fix, fix the bug or is there a bug at all?

**Comment by thinkh** [comment]
Well, I just didn't test it they way I should have tested it. 😄

**Comment by sgratzl** [comment]
can you please update the test file such that I can reproduce the initial bug

**Comment by thinkh** [comment]
I added the `groupBy` to the HTML file. You can see the effect when disabling the newly added CSS width:

image

With the width it is correct:

image

**Pull request merged**
