### PR TITLE
improve dropzones

### LINKED ISSUE #504: Increase size of drop zone for column reordering
Based on customer feedback, column reordering is a much more common operation that creating combined columns. Combining columns, however, gets a bigger drop zone. 

I'd suggest that each column has drop-zones divided into 1/3s.

left 1/3 -> drop to the left
middle 1/3 -> group
right 1/3 -> drop to the right

### PR DESCRIPTION
**Pull request by sgratzl**
closes #504

**prerequisites**:

- [x] branch is up-to-date with the branch to be merged with, i.e. develop
- [x] build is successful
- [x] code is cleaned up and formatted

## Summary

move handle

### CODE REVIEW

**Comment by alexsb** [comment]
Awesome, thanks! 

Two comments though: 

1. The "place" indicator is as wide as it's drop zone (1/3) in one column, but should probably extend to the next column over as well, as it really doesn't matter whether I'm on the right 1/3 of column A or the left 1/3 of column B. 
2. Once a "sum" indicator appears, it's not possible to get the "place" indicator back for that column, unless you move off the column. We could still have the three drop zones aktive, even if the "sum" indicator is visible, to address this. See the problem here: 
https://user-images.githubusercontent.com/2039375/148050998-29a508db-85c5-4653-a734-fc51af783186.mov

**Comment by sgratzl** [comment]
current version:

dropper

**Comment by alexsb** [comment]
This is awesome! Works really nice. 

One more suggestion: it might be useful to render the target action (place here, sum, etc.) also (or only?) in the header that you're dragging. You can easily get into situations where the label isn't readable otherwise: 
PXL_20220113_115946149

**Comment by sgratzl** [comment]
the header image is rendered by the browser not by me, thus not sure whether I can manipulate it on the fly. Even if it would be to manipulate the original header of the column being dragged within the LineUp header row. Thus, it might be more confusing that helpful.

**Comment by alexsb** [comment]
OK, I don't think it's critical, so good to merge as far as I'm concerned.

**Comment by puehringer** [comment]
One thing I noticed: when moving a column to the right next dropzone, the column of the right neighbor is rendered above the zone. 
image

**Comment by puehringer** [comment]
> One thing I noticed: when moving a column to the right next dropzone, the column of the right neighbor is rendered above the zone. image

Any update on this issue?

**Comment by sgratzl** [comment]
> One thing I noticed: when moving a column to the right next dropzone, the column of the right neighbor is rendered above the zone.

image

**Review by puehringer — APPROVED** [review]
Works for me now as expected, I think this PR can be merged as of now 🎉

**Pull request merged**
