### PR TITLE
Set `font-family` to Font Awesome 6 when using external FA

### PR DESCRIPTION
**Pull request by thinkh**
**prerequisites**:

- [x] branch is up-to-date with the branch to be merged with, i.e. develop
- [x] build is successful
- [x] code is cleaned up and formatted

## Summary

The Font Awesome dependency has been updated from version 5 to version 6 with commit c0d29ff91cb2f147e50ac068617c816a5cbef3e7. However, the font-family has not been updated which results in broken icons. Using the the correct font family name fixes the icons.

Please note that the custom lu-font is still using/set to `Font Awesome 5`.

### CODE REVIEW

**Comment by sgratzl** [comment]
make sense,

do you know whether there is a fontawesome variable available which we could use to avoid that in the future?

**Comment by thinkh** [comment]
Good idea! There is a variable for it. I can change it next time I'm at a computer again or you do it quickly. 

https://github.com/FortAwesome/Font-Awesome/blob/6.x/scss/_variables.scss#L6

**Comment by thinkh** [comment]
@sgratzl I changed our SCSS to use the Font Awesome variables. Please have a look again.

**Review by sgratzl — APPROVED** [review]
👍

**Pull request merged**
