### PR TITLE
Added exports (especially for ui/toolbar.ts)

### LINKED ISSUE #243: Missing toolbar.ts export
* Release number or git hash: 4.0.0-alpha.12
 * Web browser version and OS: -

### Observed behavior
https://github.com/lineupjs/lineupjs/blob/lineup-v4/src/ui/toolbar.ts is not part of the exports of https://github.com/lineupjs/lineupjs/blob/lineup-v4/src/ui/index.ts, and therefore not accessible by applications. 

### Expected behavior
For overriding purposes (i.e. passing the `toolbar` object in the `customOptions`) we would need access to `toolbarActions` to override defaults, as there is no other way to alter LineUp defaults: 
```
customOptions: {
    toolbar: {
          filterCategorical: {
            ...toolbarActions.filterCategorical,
            title: 'Filter &hellip;',
            options: {shortcut: true}
          },
    }
}
```

### PR DESCRIPTION
**Pull request by puehringer**
closes #243 

**prerequisites**: 
 * [x] branch is up-to-date with the branch to be merged with, i.e. develop
 * [x] build is successful
 * [x] code is cleaned up and formatted 
 * [x] tested with Firefox 52, Firefox 57+, Chrome 64+, MS Edge 16+

### Summary
Added exports/removed internal-decorator for some important functions used in toolbars/custom dialogs.

### CODE REVIEW

**Comment by sgratzl** [comment]
what is the rational and use cases to export all those private methods? all of them are just used to make internal code simpler but barely have any external use

**Comment by puehringer** [comment]
@sgratzl As I mentioned in the issue (https://github.com/lineupjs/lineupjs/issues/243), the `toolbar` exports are required when overriding the default behaviour of toolbars: 
```
customOptions: {
    toolbar: {
          filterCategorical: {
            ...toolbarActions.filterCategorical,
            title: 'Filter &hellip;',
            options: {shortcut: true}
          },
    }
}
```
There is no other way to do this as I am aware of?

The other exports become handy when you are writing custom dialogs for i.e. categorical data and need to check the `isCategoryIncluded`. I don't see a reason to reimplement these specific function?

**Comment by thinkh** [comment]
@sgratzl Is this PR fine for you? If yes, please merge.

**Comment by sgratzl** [comment]
> There is no other way to do this as I am aware of?

```
LineUpJS.defaultOptions()
```
returns the whole configuration object that is used by default by LineUp thus also including default values for the toolbar. 

in my opinion there is always the trade off between opening the API too much and force a developer to implement some extra functions. The more functions are exported the
 * more difficult it is to change things without creating a breaking change
 * more difficult it is to ensure that all the names are meaningful and unique since it is a flat export
 * more difficult the API gets and it is easier to get lost in all the functions. 

I understand the argument when it is about complex functions. But e.g. the ones in `toolbar.ts` are just internal to simplify the code without a bigger logic behind it. Understanding the utility functions is more difficult than implementing the behavior one wants.

**Comment by puehringer** [comment]
I think we can close this PR with the `LineUpJS.defaultOptions()` being a good alternative.

**Pull request closed without merging**
