### PR TITLE
Improve data mapping dialog

### LINKED ISSUE #285: Wrong behavior of data mapping dialog
* Release number or git hash: 9d9c5deed03dae683cfe763821ce6a21e7c8a090
 * Web browser version and OS: Chrome 80

### Steps to reproduce

1. Open data mapping dialog of a numerical column
1. Shift + Click on point
1. Reset dialog

### Observed behavior

lineup-reset-datamapping

* There is no live preview when changing the settings. Is this on purpose?
* If one is clicking on a point with Shift + Click to specify exact values, it is unclear how to close the popup again
* Unclear how the `Remove Mapping Line` works
* `Reset to default values` doesn't reset domain min/max

### Expected behavior

The issues above should be adressed and fixed.

### PR DESCRIPTION
**Pull request by sgratzl**
based on #289 for cypress utils

closes #285, #286 

**prerequisites**: 
 * [x] branch is up-to-date with the branch to be merged with, i.e. develop
 * [x] build is successful
 * [x] code is cleaned up and formatted 
 * [ ] tested with Firefox 52, Firefox 57+, Chrome 64+, MS Edge 16+

### CODE REVIEW

**Comment by sgratzl** [comment]
image

image

image

**Comment by thinkh** [comment]
Thanks for the improvement! The dialog is already much better to use. 
While testing I found a few more suggestions and a bug.

### Bug: Wrong state 

1. Drag the minimum mapping line
1. Change the value in the min input field

The background pattern is moved, but the mapping line is still diagonal.

lineup-data-mapping

### Inputs for output domain

I'd suggest add input fields to the normalized output domain. This would make it easier for the user to evaluate and adjust the value without opening the mapping line dialog.

grafik


### Interaction with mapping lines and dialogs

While it is really convenient to add additional mapping lines, I found a bit cumbersome to open the mapping dialog and remove mapping lines.

* ✔ Add mapping line with click on the input and output domain works fine
* ✔ Dragging the circles and lines also works fine
* 🆕 Either single click or double click on the circles should open the mapping line dialog
   * Click on circle = Open mapping line dialog
   * Drag'n'drop = Move circle or line (as it is now)
* 🆕 Remove mapping line: Once the user hovers over a line (and it is highlighted in orange) and then presses the _Del_ key it will be removed.
   * That would be an alternative shortcut for power users for the remove mapping line button
* 🆕 In general: Keep the selected mapping line highlight as long the mapping line dialog is open
   * Currently it is unclear which mapping line is selected for the mapping line dialog
     grafik
* 🆕 The mapping line dialog should close (= canceled) when the user clicks anywhere in the data mapping dialog
   * Currently the user must confirm/cancel the mapping line dialog which is really cumbersome and does not match with all other dialogs that gets closed once the user clicks outside

### Margin remove mapping line button

Can you add `margin-top: 15px` to the remove mapping line button? That would give it a separation from the input field.

grafik

**Comment by sgratzl** [comment]
> I'd suggest add input fields to the normalized output domain. This would make it easier for the user to evaluate and adjust the value without opening the mapping line dialog.

in case the user does an inverted mapping (lines crossing) it wouldn't be clear which input belongs to which line. Thus, I never added the direct input fields.

**Comment by thinkh** [comment]
> > I'd suggest add input fields to the normalized output domain. This would make it easier for the user to evaluate and adjust the value without opening the mapping line dialog.
> 
> in case the user does an inverted mapping (lines crossing) it wouldn't be clear which input belongs to which line. Thus, I never added the direct input fields.

Valid point! I agree that this can lead to confusion. We can leave this as it is.

Would be possible to encode the minimum and maximum mapping line different than intermediate once? That would make it easier to distinguish them even when they are crossed.

**Comment by sgratzl** [comment]
>  Either single click or double click on the circles should open the mapping line dialog
> 
>     * Click on circle = Open mapping line dialog
> 
>     * Drag'n'drop = Move circle or line (as it is now)

I implemented dblclick

>     * 🆕 Remove mapping line: Once the user hovers over a line (and it is highlighted in orange) and then presses the _Del_ key it will be removed.

I don't think this is helpful it would be the first time LineUp that hover + pressing a key would do something. I don't think that the mouse position + a key press doing an action will be a good UX cause it is too error prune. 



>  In general: Keep the selected mapping line highlight as long the mapping line dialog is open
> 
>     * Currently it is unclear which mapping line is selected for the mapping line dialog

done


>     * 🆕 The mapping line dialog should close (= canceled) when the user clicks anywhere in the data mapping dialog

done


> Can you add `margin-top: 15px` to the remove mapping line button? That would give it a separation from the input field.

done

> Would be possible to encode the minimum and maximum mapping line different than intermediate once? That would make it easier to distinguish them even when they are crossed.

I think that they are bound to the end and that they are the only ones having a solid dot at the top is enough. Moreover, there are only rare cases in which really more than two mapping lines exist.

**Comment by thinkh** [comment]
Thanks for your changes. It looks better now.

I still found a small bug: When setting a value in the mapping line dialog (and confirm) the lines are not updated.

lineup-datamapping-dialog

### Additional usability improvements

**Tooltip/value while dragging**

Can we add a tooltip or show the current value _while_ dragging the slider? Then users would see the actual value without opening the mapping line dialog. We have already a similar functionality for the filter dialog (I know we have only two handles there).

lineup-filter-dialog

**Remove mapping line button**

Can you please move up the _remove mapping line_ button to the top? That way the user can faster remove the mapping line. We should also add a trash can icon and change the style to something like in the toolbar or the apply/cancel/reset button (so no HTML button style).

**Comment by thinkh** [comment]
> I don't think this is helpful it would be the first time LineUp that hover + pressing a key would do something. I don't think that the mouse position + a key press doing an action will be a good UX cause it is too error prune.

Ok, I agree.


> I think that they are bound to the end and that they are the only ones having a solid dot at the top is enough. Moreover, there are only rare cases in which really more than two mapping lines exist.

Ok, we can leave it like it is.

**Comment by sgratzl** [comment]
re tooltip can you create a mockup picture how it should look like. cause atm. there is no space for that

**Comment by thinkh** [comment]
Thanks for the last changes. I had a look at the remove mapping line button and it looks already better. However, I would make the color a bit darker, so that it looks a bit less like a disabled button. 

grafik

As for the tooltip it could look like this:

grafik

I increased the height of the boxes by 25px and added a span at the top and below the handles. Do you think that would work?

**Comment by sgratzl** [comment]
2020-04-14 10_42_43-LineUp Builder Test

**Comment by thinkh** [comment]
Nice change!

I found another bug with the reset of the data mapping dialog.

**Steps to reproduce**

1. Open _builder.html_
1. Open data mapping dialog of numerical column 
1. Change nothing and only click reset

**Observed behavior**

lineup-data-mapping-reset

Error in the dev tools

```
MappingDialog.ts:240 Error: <line> attribute x2: Expected length, "NaN".
(anonymous) @ MappingDialog.ts:239
forEach @ ADialog.ts:174
updateLines @ MappingDialog.ts:236
destroyed @ MappingDialog.ts:24
destroy @ MappingLineDialog.ts:188
(anonymous) @ MappingDialog.ts:210
createMappings @ MappingDialog.ts:210
reset @ MappingDialog.ts:248
reset.onclick @ ADialog.ts:135
```

**Expectation**

I'm confused by the lines and the min/max value changes. I would expect that reset does not change anything when I see already the default values (i.e., open the dialog for the first time). I think the number format should remain the same and the lines should not change at all.

**Comment by mstreit** [comment]
Very nice. Can we get rid of the gray frame around the input and output domain?

**Comment by sgratzl** [comment]
image

**Comment by sgratzl** [comment]
> I found another bug with the reset of the data mapping dialog.

done

**Pull request merged**
