### PR TITLE
Violin Chart

### LINKED ISSUE #494: Violin Plots for Numerical Column Groups
Implement a Violin-plot of single-sided KDE plot (whatever looks better) to replace box-plots. 

For small groups, don't show the violin plot, but show jittered dots instead (violin plots and box plots don't really work for small N; where N < 5-10)

Optionally, allow to combine violin plots and dot plots in general?

### PR DESCRIPTION
**Pull request by sgratzl**
closes #494 

**prerequisites**:

- [x] branch is up-to-date with the branch to be merged with, i.e. develop
- [x] build is successful
- [x] code is cleaned up and formatted

## Summary

creates a basic violin chart renderer

image

### CODE REVIEW

**Review by thinkh — COMMENTED** [review]
Thanks for the feature. To me this looks good.

@alexsb Do you agree and would approve this PR?

**Review by thinkh — APPROVED** [review]

**Comment by alexsb** [comment]
This looks good. Should we increase the contrast a bit, i.e., make the body and the outlines darker? 

Thanks!

**Comment by sgratzl** [comment]
re brightness -> requires #514 to be merged first

**Comment by puehringer** [comment]
@alexsb Does this feature now work as intended? If yes, I think we can merge it.

**Comment by alexsb** [comment]
Yes, this looks good. Thanks for the work and the ping!

**Review by alexsb — APPROVED** [review]

**Pull request merged**
