### PR TITLE
Update browserlist and issue templates

### LINKED ISSUE #202: Update list of supported browsers
According to the list of tested browsers in the package.json, LineUp supports the current versions:

https://github.com/lineupjs/lineupjs/blob/85df597de875fc986e258df0c4d11fdfd5f72b24/package.json#L38-L43

The versions are also listed as tested browsers in the [current PR template](https://github.com/lineupjs/lineupjs/blob/master/.github/PULL_REQUEST_TEMPLATE.md):

> tested with Firefox 52, Firefox 57+, Chrome 64+, MS Edge 16+

In my opinion, we can update the list to the following minimum versions:

* [Firefox ESR](https://support.mozilla.org/de/kb/firefox-esr-release-cycle) (currently Firefox 68)
* Last 2 Firefox versions (e.g., currently Firefox 70 - 2 = minimum version 68 = ESR)
* Last 2 Chrome versions (e.g., currently Chome 78 - 2 = minimum version 76)
* [Microsoft Edge 44 with EdgeHTML 18+](https://en.wikipedia.org/wiki/Microsoft_Edge#EdgeHTML_(2014%E2%80%932019)_2) (last version 05/2019)
* [Microsoft Edge 79 with Chromium](https://en.wikipedia.org/wiki/Microsoft_Edge#Chromium_(2019%E2%80%93present)) (to be released in 01/2020)

At the end this will be the updated browserlist spec:

```json
  "browserslist": [
    "Firefox ESR",
    "last 2 Firefox versions",
    "last 2 Chrome versions",
    "last 5 Edge versions"
  ],
```

Note: `last 5 Edge versions -> Edge >=18 -> Edge 82, Edge 18` (see [browserlist issue](https://github.com/browserslist/browserslist/issues/373#issuecomment-549897804)). We might need to update this later as Edge will also have enterprise releases (similar to Firefox ESR).

@sgratzl Are you fine with the updated browser list?

### PR DESCRIPTION
**Pull request by sgratzl**
closes #202

**prerequisites**: 
 * [x] branch is up-to-date with the branch to be merged with, i.e. develop
 * [x] build is successful
 * [x] code is cleaned up and formatted 
 * [ ] tested with Firefox 52, Firefox 57+, Chrome 64+, MS Edge 16+

### Summary
 
update the browser list along with the PR template to reflect it. Moreover, I added a bunch of issue templates for better issue management

### CODE REVIEW

**Comment by sgratzl** [comment]
circleci fails with an unknown: permission denied for unpacking cache error

**Comment by thinkh** [comment]
@sgratzl It seems that restoring the cache for the `/root/.npm` directory does not work (anymore?). Should I wait for a fix for the CircleCI error?

**Comment by sgratzl** [comment]
> 
> 
> @sgratzl It seems that restoring the cache for the `/root/.npm` directory does not work (anymore?). Should I wait for a fix for the CircleCI error?

seems like we have a faulty machine cause another build (https://app.circleci.com/pipelines/github/lineupjs/lineupjs/460/workflows/93ea315b-d9f4-4ed1-a2ce-4b98e43531f4/jobs/834) works like a charm

**Comment by thinkh** [comment]
@sgratzl I merged this PR and now the lineup-v4 branch has CircleCI errors...

**Pull request merged**
