### PR TITLE
add tick vis, adjust lightness of bars vs ticks/dots

### LINKED ISSUE #495: New Numerical Item Visualization: Tick
A vertical Tick might be a bit easier to see than just a dot.

### PR DESCRIPTION
**Pull request by sgratzl**
closes #495

**prerequisites**:

- [x] branch is up-to-date with the branch to be merged with, i.e. develop
- [x] build is successful
- [x] code is cleaned up and formatted

## Summary

image

also add a categorical tick version (part of #488 )

image

### CODE REVIEW

**Review by thinkh — COMMENTED** [review]
From the specification it looks fine. However, the ticks that are at the left or right border of the cell are cut-off and look thinner. Does it make sense to shift the tick slightly so that it is always completely visible?

grafik

@alexsb Please have a look at the netlify preview and answer the following questions:

1. Does the visualization title "Tick" makes sense for you?
2. General question: when would you use the tick visualization? To me the (default) bar visualization works much better:

**Ticks**

grafik

**Bars**

grafik

**Comment by alexsb** [comment]
Second @thinkh on the small ticks on the side - I wouldn't shift a tick though, but maybe make the render area a bit bigger (or the scale's region) so that this doesn't happen. 

Re name: I think "tick" is good. Vega also uses that term: https://vega.github.io/vega-lite/docs/tick.html

**Comment by alexsb** [comment]
I've created a related issue in #524

**Comment by sgratzl** [comment]
changes:
 * fixes #525  - adjust lightness and smaller NA marker
 * add labels for dot and ticks

image

**Comment by alexsb** [comment]
Nice!

Here are two examples: 

Screen Shot 2021-12-24 at 10 49 50 AM

image

I'd say the ticks appear a bit darker than the dots, and the bars appear a bit lighter than the dots. So maybe try decreasing lightness for the bars and increasing lightness for the ticks a bit.

**Comment by sgratzl** [comment]
take a look:
image
image

**Comment by alexsb** [comment]
That looks great!

**Comment by alexsb** [comment]
Michael, this is ready to review and merge.

**Review by puehringer — APPROVED** [review]
Looks good to me!

**Pull request merged**
