### PR TITLE
missing group values

### LINKED ISSUE #322: Show missing value dash for boxplot group renderer
* Release number or git hash: https://github.com/lineupjs/lineupjs/commit/4976c18e6ddc549217a9700e63a963fbce12416c
 * Web browser version and OS: Chrome 81

### Steps to reproduce

 1. Group and aggregate a group with only missing values

### Observed behavior

grafik

A boxplot is shown eventhough only missing values are available.

### Expected behavior

grafik

A missing value dash should be shown instead of the empty boxplot. This can be easily done by adding the `lu-missing` to the boxplot cell group renderer.

### PR DESCRIPTION
**Pull request by sgratzl**
closes #322

**prerequisites**: 
 * [x] branch is up-to-date with the branch to be merged with, i.e. develop
 * [x] build is successful
 * [x] code is cleaned up and formatted 
 * [ ] tested with Firefox 52, Firefox 57+, Chrome 64+, MS Edge 16+

### Summary

proper detect missing groups

### CODE REVIEW

**Comment by sgratzl** [comment]
don't know why the test is not working: the screenshot from circle ci shows the correct behavior:

image

**Comment by sgratzl** [comment]
I assume you are at the `sgratzl/missinggroup` branch?

**Comment by thinkh** [comment]
Yes.

grafik

**Comment by sgratzl** [comment]
> I'm using the standalone Cypress. With the fresh build it works as expected.

as an alternative you can use `npm run cy:start` along with `npm start` with then uses the local hosted version

**Pull request merged**
