### PR TITLE
fix: shifted hidden column are causing problems

### LINKED ISSUE #404: visibility error
* Release number or git hash: lineupjsx: 4.0.0 | lineupjs: 4.1.1
 * Web browser version and OS: Google Chrome Version 87.0.4280.141 on Windows 10

### Steps to reproduce

 1. open react example in codepen: [https://codepen.io/sgratzl/pen/yvJpWQ](url)
 2. add `<LineUpJS.LineUpCategoricalColumnDesc column="cat" categories={cats} color="green" visible={false} />` in the beginning
 3. try to remove a column that would come after the previously added one

### Observed behavior
 * When adding the "visible={false}" property to a column description, it is not possible to delete any column that comes after this one without issue. When trying to delete such a column, it deletes the column after the selected one and sometimes there also occurs an error that causes the header to not render correctly anymore. 
 * **edit: also happens in lineupjs when adding .custom("visible", false) to the column builder**
	  ```
	  Uncaught TypeError: Cannot read property 'getOrderLength' of null
	      at e.summaryCategoricalStatsD (DirectRenderTasks.js:154)
	      at e.summaryCategoricalStats (DirectRenderTasks.js:127)
	      at Object.update (CategoricalCellRenderer.js:92)
	      at t.updateHeader (RenderColumn.js:109)
	      at e.updateHeader (EngineRanking.js:256)
	      at e.updateHeader (ACellTableSection.js:49)
	      at ACellAdapter.js:366
	      at Array.forEach (<anonymous>)
	      at e.t.recreate (ACellAdapter.js:364)
	      at e.recreate (ACellTableSection.js:197)
	  e.summaryCategoricalStatsD @ DirectRenderTasks.js:154
	  e.summaryCategoricalStats @ DirectRenderTasks.js:127
	  update @ CategoricalCellRenderer.js:92
	  t.updateHeader @ RenderColumn.js:109
	  e.updateHeader @ EngineRanking.js:256
	  e.updateHeader @ ACellTableSection.js:49
	  (anonymous) @ ACellAdapter.js:366
	  t.recreate @ ACellAdapter.js:364
	  e.recreate @ ACellTableSection.js:197
	  e.updateAll @ EngineRanking.js:479
	  (anonymous) @ EngineRanking.js:145
	  (anonymous) @ debounce.js:27
	  setTimeout (async)
	  (anonymous) @ debounce.js:25
	  (anonymous) @ EngineRanking.js:156
	  apply @ dispatch.js:61
	  a @ AEventDispatcher.js:97
	  t.fireImpl @ AEventDispatcher.js:100
	  t.fire @ AEventDispatcher.js:74
	  e.remove @ Ranking.js:479
	  e.removeMe @ Column.js:253
	  onClick @ toolbar.js:155
	  u.onclick @ header.js:143
	  EngineRanking.js:299 Uncaught TypeError: Cannot read property 'width' of undefined
	      at e.visibleRenderedWidth (EngineRanking.js:299)
	      at e.updateShifts (EngineRanking.js:630)
	      at e.updateSizer (ACellTableSection.js:126)
	      at e.onScrolledHorizontally (ACellTableSection.js:170)
	      at e.show (ACellTableSection.js:149)
	      at MultiTableRowRenderer.js:54
	      at Array.forEach (<anonymous>)
	      at t.onScrolledHorizontally (MultiTableRowRenderer.js:48)
	      at MultiTableRowRenderer.js:32
	      at t.handle (scroll.js:55)
	  ```

* Static or animated images showing the UI behavior
   image

### Expected behavior
 * remove column

### PR DESCRIPTION
**Pull request by sgratzl**
closes #404

**Prerequisites**:

* [x] Branch is up-to-date with the branch to be merged with, i.e. develop
* [x] Build is successful
* [x] Code is cleaned up and formatted 
* [x] Tested with Firefox ESR, latest Firefox, latest Chrome, Edge 18

### Summary
 
fixes #404 where hidden columns are causing shifting errors

### CODE REVIEW

**Review by thinkh — CHANGES_REQUESTED** [review]
This fix seems to work and does not produce errors. However, when adding the hidden `cat` column from the side panel the column is visible, but the filter is still hidden in the side panel.

lineup-visiblity

**Comment by sgratzl** [comment]
the question is what should happen with a column that is by default hidden? Should the user be able to add it at all? I changed the logic such that the user cannot add a hidden description.

**Comment by thinkh** [comment]
> the question is what should happen with a column that is by default hidden? Should the user be able to add it at all? I changed the logic such that the user cannot add a hidden description.

IMO there are two options:

1. Columns are hidden everywhere and cannot be added or used (current status with [your last commit](https://github.com/lineupjs/lineupjs/pull/411/commits/d705dbfe8df1bb1b30ec8a5644a6ecfc121b2965))
2. Columns are hidden in the ranking by default (similar to `initialRanking: false`in TDP), but can be added by the user (previous status)

I'd argue that option 1 does not make a lot of sense, because the column could be filtered out from the dataset before passing it to LineUp or one could simply not create a LineUp column for this data column. In both cases we would have the same result that the column is not available or visible in the UI.

Option 2 is probably prefered, because it gives users the option to add the column later on demand. In my opinion the previous state was fine, the only thing missing was the filter in the side panel when adding a hidden column to the ranking (see [my last comment](https://github.com/lineupjs/lineupjs/pull/411#pullrequestreview-606234686)).

**Comment by sgratzl** [comment]
> Option 2 is probably prefered, because it gives users the option to add the column later on demand. In my opinion the previous state was fine, the only thing missing was the filter in the side panel when adding a hidden column to the ranking (see [my last comment](https://github.com/lineupjs/lineupjs/pull/411#pullrequestreview-606234686)).

why adding a column to the (initial) ranking and mark it as hidden? Why cannot you just use the builder to build a ranking which doesn't include this column ?

**Comment by thinkh** [comment]
I think we are still not on the same page and there are two points, we should discuss:

1. Define which columns should be available in the add column dialog
2. Define which columns should be shown/hidden in the (initial) ranking

I thought the first one is automatically done by adding the dataset to the builder (e.g., `LineUpJS.builder(arr)`) or registering it to the data provider. If a developer wants to make certain columns unavailable the properties must be filtered out before passing `arr` to the builder.

As for the second point, I agree with your suggestion to exclude the column from the builder and also thought that this should do the trick. Take for example the _visibility.html_ demo with the removed `cat` column builder:

```js
.column(LineUpJS.buildStringColumn('d').label('Label').alignment('right').width(100))
// .column(LineUpJS.buildCategoricalColumn('cat', cats).color('green').hidden())
.column(LineUpJS.buildCategoricalColumn('cat2', cats).color('blue'))
.column(LineUpJS.buildNumberColumn('a', [0, 10]).color('blue'));
```

The `cat` column is not visible in the ranking, but also not available in the add column dialog:

grafik

What is the setup to hide a column in the (initial) ranking, but let the user add it on demand?

**Comment by sgratzl** [comment]
> What is the setup to hide a column in the (initial) ranking, but let the user add it on demand?

the builder automatically calls `.defaultRanking()` when no explicit ranking is defined. e.g. take a look at `builder2.html`. You can create your own rankings easily and define which columns you wanna include. The `.defaultRanking()` will include all columns by default

```js
const builder = LineUpJS.builder(arr);

// manually define columns
builder
  .sidePanel(true, true)
  .column(LineUpJS.buildStringColumn('d').label('Label').alignment('right').width(100))
  .column(LineUpJS.buildCategoricalColumn('cat', cats).color('green'))
  .column(LineUpJS.buildCategoricalColumn('cat2', cats).color('blue'))
  .column(LineUpJS.buildNumberColumn('a', [0, 10]).color('blue'));

const ranking = LineUpJS.buildRanking()
  .supportTypes()
  .column('d')
  .column('cat')
  .column('a')
  .groupBy('cat')
  .sortBy('a', 'desc')

builder.ranking(ranking);

const lineup = builder.build(document.body);
```

**Comment by sgratzl** [comment]
as far as I remember: The use case for the `hidden` flag of columns is quite rare. You want a column part of the ranking which is not visible to the user. For example when you wanna control a column from the outside which sole purpose is to control the ranking with no user interaction.

**Review by thinkh — APPROVED** [review]
You are right, I missed the `.defaultRanking()` and explicitly defining a ranking is the solution for this use case. In this case we are good to merge.

**Pull request merged**
