### PR TITLE
Make renderer and utils function publicly available (i.e., remove @internal markers)

### LINKED ISSUE #203: let the user show / hide numbers in numeric columns
We would like to use numeric columns in LineUp and be able to show hide numeric values (preferrably on a global **and** on a column basis).

So the user should be able to show / hide numbers depending on what the user prefers.

There is already an option in the `BarCellRenderer` https://github.com/lineupjs/lineupjs/blob/master/src/renderer/BarCellRenderer.ts

However it is by default false and, as far as I can see, cannot be set, neither when instantiating the renderer nor during runtime: https://github.com/lineupjs/lineupjs/blob/develop/src/renderer/index.ts 

Moreover it is defined as `@internal` so it is also not possible to subclass and change the renderer slightly

The only option I can currently see is copying the code and adapt it there. Can we add a feature to set this option at runtime or at least be able to set the option?

Best would be of course to set the option of the renderer at runtime from the outside. Or is there already the possibility to achieve this?

There is of course also the hacky option to simply override it via CSS, but there should be another way

### PR DESCRIPTION
**Pull request by lehnerchristian**
closes #203

**prerequisites**: 
 * [x] branch is up-to-date with the branch to be merged with, i.e. develop
 * [x] build is successful
 * [x] code is cleaned up and formatted 
 * [ ] tested with Firefox 52, Firefox 57+, Chrome 64+, MS Edge 16+

### Summary
 
* Remove `@internal` marker from Renderer, which makes them publicly available in the .d.ts files

### CODE REVIEW

**Comment by dvmichaelpuehringer** [comment]
@thinkh  @lehnerchristian @sgratzl would you mind also removing the `@internal` from the dialogs in `ui/dialogs/`?. This would make it much easier to extend/modify the behavior of the toolbar actions. For example, checking the `Filter rows containing missing values` when filtering categories by default.

**Comment by lehnerchristian** [comment]
would be fine for me. @thinkh , what would you say?

**Comment by thinkh** [comment]
@dvmichaelpuehringer I'm fine with this change. Could you please open another issue/PR for this?

@lehnerchristian Could you please file an additional PR for the LineUp 4 then?

**Comment by sgratzl** [comment]
re internal: ok

> For example, checking the `Filter rows containing missing values` when filtering categories by default.

don't get it tbh, you mean when the user click on the filter icon it will automatically check this one checkbox?

**Comment by dvmichaelpuehringer** [comment]
@sgratzl Yes, as there is currently no way of passing a default configuration unfortunately, this would be one way of checking it by default. I.e. when a filter is applied, filter the missing values if it was not unchecked.

**Comment by lehnerchristian** [comment]
> @dvmichaelpuehringer I'm fine with this change. Could you please open another issue/PR for this?
> 
> @lehnerchristian Could you please file an additional PR for the LineUp 4 then?

sure!

**Comment by lehnerchristian** [comment]
@thinkh , @sgratzl I've also removed the `@internal` markers from the `utils.ts` file as they may also be interesting for when subclassing from Renderers. so please check my latest commit again and merge if it's ok for you

**Pull request merged**
