### PR TITLE
 use background selection indicator

### LINKED ISSUE #574: Highlight Background instead of Frame for Selections
Frames are a little more brittle, we should use background highlighting. Here's a mock-up: 

image

Colors
Click: FFCF76
Hover: FFE8BE

### PR DESCRIPTION
**Pull request by sgratzl**
closes #574 

**prerequisites**:

- [x] branch is up-to-date with the branch to be merged with, i.e. develop
- [x] build is successful
- [x] code is cleaned up and formatted

## Summary

image

BREAKING UX CHANGE

### CODE REVIEW

**Comment by thinkh** [comment]
It looks already good to me. While playing around I saw that the selection indicator uses still the "old" darker orange and the missing value dash could be a bit darker for selected rows if it is not too much effort.

grafik

**Comment by thinkh** [comment]
@alexsb Could you also please have a look in the deploy preview if the selected rows look and work as expected?

**Comment by alexsb** [comment]
Overall great. 

I'd turn the other marks a bit darker; as Holger said the "none" - marks, but also the bars: 

image

Maybe 15% more saturation? Here, I changed it to rgb(160, 160, 160), which looks nice in isolation, but of course would have to be judged as a whole: 

image

I'd do this for all bars, irrespective of them being selected or not, as it's pretty low contrast generally. 

Also second Holger's points.

**Review by alexsb — COMMENTED** [review]
See my comment.

**Comment by sgratzl** [comment]
take a look:

image

**Review by thinkh — APPROVED** [review]
Thanks. It looks good to me. Waiting for @alexsb approval.

**Review by alexsb — APPROVED** [review]
Looks great. Ready to merge!

**Comment by mstreit** [comment]
Very nice, thanks!

**Pull request merged**
