### PR TITLE
add option to filter to selected rows

### LINKED ISSUE #394: Add filter option to selection column
Currently the selection column can only be grouped and sorted. 

grafik

It would be interesting to filter the ranking by the selection column. The user should be able to select to show/hide the selected or unselected rows. Probably the filter dialog would look similar to the boolean column filter dialog (but without the missing values).

grafik

### Open questions

* Can the filter be re-evaluated/applied each time a row is selected/unselected? Example: The filter is applied to show only the selected rows. I would expect that a previously selected row gets hidden, once the user unselects the row.

### PR DESCRIPTION
**Pull request by sgratzl**
Closes #394 

**Prerequisites**:

* [x] Branch is up-to-date with the branch to be merged with, i.e. develop
* [x] Build is successful
* [x]  Code is cleaned up and formatted 

### Summary

add option to filter to the currently selected rows: 
 
image

### CODE REVIEW

**Review by thinkh — COMMENTED** [review]
Thanks, that works well. 👍 

I'm still thinking if we can improve the wording a bit. I will also discuss this with @puehringer in tomorrows meeting.

**Review by thinkh — CHANGES_REQUESTED** [review]
We still found a bug with the simple.html demo: We got a state where we initially filtered for 10 rows and then selected 5 rows. Afterwards the keep current filter showed the wrong result:

grafik

**Usability**

* Hide/Disable the option _remove filter_ and _keep current filter_ when no filter is applied:
   grafik
* Show a message when no row is selected and no filter is applied: `Select rows to apply this filter.`


**Wording**

* Capitalize first letter of each option
* Avoid line break for each label

**Comment by sgratzl** [comment]
> current filter showed the wrong result:

what should it show? 

the second line is imo correct, since you set and saved a filter that is filtering to 10 rows (in this column)
the third line is correct, too since you selected five rows.

**Comment by thinkh** [comment]
> > current filter showed the wrong result:
> 
> what should it show?
> 
> the second line is imo correct, since you set and saved a filter that is filtering to 10 rows (in this column)
> the third line is correct, too since you selected five rows.

The label of the radio buttons are correct, but the displayed rows in the background are not. In my opinion the visible rows in the background should be equal to the number of rows in the label. You can see that _keep current filter_ does not work anymore once _filter currently selected_ was selected.

lineup-selectionfilter

> can you create a sketch, please with all the different variants (no filter and no rows selected, no filter but some rows, filter but no rows, filter and rows)

I will do this.

**Comment by sgratzl** [comment]
> I will do this.

ping

**Comment by thinkh** [comment]
In the following you can find the mockups how the filter dialog could look like.

### No row selected + no filter applied

grafik

**Changes**

* Remove radio buttons and replace with text

**Alternative solution**

* Disable _filter_ action in more menu and add the text to a tooltip


### Rows selected + no filter applied

grafik

**Changes**

* Rename _Remove filter_ to _No filter (<#total> rows)_
* Hide _Keep current filter_
* Rename _Filter currently selected_ to _Set filter to current selection_

If possible, we should make the row count consistent with the categorical filter dialog and display `<#filtered>/<#total> rows` right aligned.

grafik


### Rows selected + filter already applied

grafik

**Changes**

* Identical with current implementation + renamings from above

**Comment by thinkh** [comment]
Thanks for your changes, it works now nicely. I have only two remarks left.

Why has `No filter` a `?` in case a filter is already applied, but not for the first time?

First time the filter is set:
   
grafik

Filter is already set:

grafik

---

Is it possible to right align the numbers like in the categorical filter dialog?

grafik

grafik

**Comment by sgratzl** [comment]
> Is it possible to right align the numbers like in the categorical filter dialog?

done

**Comment by sgratzl** [comment]
@thinkh anything missing that this can be merged? with more issues on the way regarding selection column it is difficult to avoid conflicts without that

**Review by thinkh — COMMENTED** [review]
Thanks for your implementation. Looks good now.

**Review by thinkh — APPROVED** [review]

**Pull request merged**
