### PR TITLE
optimize visualizations

### LINKED ISSUE #458: Spark Line Renderer for Group seems to be on wrong coordinate system?
When I visualize a time series dataset and group, then choose the spark line renderer, the spark lines seem to be rendered wrongly: 
image

They seem to be too far down and not go all the way to the right (the last cell is empty). The all the way to the right is probably cause by the "axis" starting at the left edge of the cell, instead of the middle of the cell. 

**To Reproduce**

* Go to https://lineup.js.org/app/#soccer
* Group by Foot
* Switch group visualization for "Goals" to "Sparkline"

**Expected behavior**

Sparklines should horizontally start at the middle of the first cell and end at the middle of the last cell. 
They should not overlap with the heat map fields below.

### LINKED ISSUE #463: Remove "UpSet" Visualization in Lineup Categorical
The categorical upset visualization doesn't make much sense: 

image

Why? 

* The round marks really only look good if they are circles, which is unlikely to happen in the general case. 
* The matrix visualization (in grayscale) does a better job
* The name is confusing (it has a bit of upset style, but it's not really related to upset)

### LINKED ISSUE #466: Rename Categorical Item visualization from "Color" to "Color & Label"
Color simply doesn't sufficiently describe it.

### LINKED ISSUE #471: "Dot" visualization for individual numerical items could be bigger/darker
I think it makes sense to have slightly different marks for individual dots in a row, and dots as part of a group visualization: 

image

The dots here could be bigger/darker. The smallness and transparency is useful in aggregate, but not for the individual cells.

### PR DESCRIPTION
**Pull request by sgratzl**
closes #471, closes #466, closes #463, closes #458

**prerequisites**:

- [x] branch is up-to-date with the branch to be merged with, i.e. develop
- [x] build is successful
- [x] code is cleaned up and formatted

## Summary

re #471 
image

### CODE REVIEW

**Comment by thinkh** [comment]
To me the changes look good. 

@alexsb Please have a look at the changes. You can use the deploy preview to test the changes: https://deploy-preview-479--lineupjs.netlify.app/all_column_types.html Thanks.

**Comment by alexsb** [comment]
Thanks for this, I think these issues are fixed, though here are some consequences that we might have to fix as well: 

Re #471: 
Because of the larger dot symbol, issues that appear when a value is at the min/max of the scale, with partial clipping of the dot are aggrevated: 
image

This could be fixed by adding a padding, padding the range a bit, or by allowing the renderer to draw outside the box. 

Re #458, I can't get the expected behavior, of multiple overlaid sparklines working in the deploy preview: 

image

Here, I would have expected to see two sparlines for "Row 7, Row 9".

**Comment by sgratzl** [comment]
re clipping: 

image

re sparklines:

1. https://deploy-preview-479--lineupjs.netlify.app/builder4.html
2. group by Cat and collapse the first group
3. change visualizations for As to Item = Sparkline and Group = Sparklines 

image

**Comment by alexsb** [comment]
Looks great, thanks. 

One more thought (and this should be a separate issue, but might be a minor fix that goes with this PR): 

It might look better to give the strip plots a bit less height, so that they can be more clearly recognized as belonging to separate rows: 

image

E.g., reducing the height by 10% might look better?

**Comment by sgratzl** [comment]
image

**Comment by alexsb** [comment]
Awesome, thanks! Good to merge as far as I'm concerned.

**Comment by sgratzl** [comment]
@thinkh anything missing that this can be merged? with more issues on the way regarding visualization it is difficult to avoid conflicts without that

**Review by thinkh — APPROVED** [review]
Thanks, looks good.

**Pull request merged**
