### PR TITLE
selection indicator

### LINKED ISSUE #528: Show off-screen visualization for selected items.
Problem: when Items are selected from "outside of" lineup, but selection is shown in lineup, selections are not easy to spot because they could be off-screen. 

Solution: 
We should use off-screen visualization, similar to what is available in browsers or code editors: 
image

Approaches: 
 * We could do it directly on a scroll-bar, though that might be a bit hard to control for in different platforms. 
 * We could do it as a "manual" scroll bar on the right edge of lineup. 

Here is a possible mock-up: 

image

Question: 
Should this be a part of lineup or a separate view? 

Alternatives: 
* We discussed sorting the selected items to the top, but that would "destroy" a ranking. An off-screen visualization would also give a good indication of how the items are distributed based on the ranking. 
* We discussed overview mode, but concluded that such a transition would be too invasive. 
*  We discussed a "bubble" that points to selected items above or below, similar to what's implemented in Triage: 
image
But decided that this wouldn't help with getting an overview of the selection relative to the sorting, and would be most useful in the context of a few selections. But such a pointer could be a useful addition. 

Considerations: this is a problem that we might also encounter in other views, which would speak for an independent implementation. However, that's probably hard in practice, since each view controls its spatial layout.

### PR DESCRIPTION
**Pull request by sgratzl**
closes #528

**prerequisites**:

- [x] branch is up-to-date with the branch to be merged with, i.e. develop
- [x] build is successful
- [x] code is cleaned up and formatted

## Summary

add selection indicator on the right

image

### CODE REVIEW

**Comment by sgratzl** [comment]
@alexsb take a look again, it should be better but there are limits since I have to change the position of the bar each time you scroll

**Comment by alexsb** [comment]
It's still pretty jittery? 

Not sure what a good solution would be. Just as a sanity check: there's no simple solution, like a css `position: absolute` here? Or moving the bar into a side-bar similar to the histograms/column configs on the right?

If not, then maybe fade out while we're scrolling? [though that defeats the purpose a bit]

**Comment by alexsb** [comment]
This is perfect! Thank You!

**Comment by puehringer** [comment]
@sgratzl Thanks, I briefly tested this PR using https://deploy-preview-535--lineupjs.netlify.app/big.html and found an issue: 

1. Select some range in the ranking (the selection hint is correct)
2. Sort by some column (in this case Number2)
3. The selection hint does not update and stays on the "old" position
Selection_Test

I suppose it should update this selection hint with order changes.

**Comment by sgratzl** [comment]
> I suppose it should update this selection hint with order changes.

fixed

**Review by alexsb — APPROVED** [review]

**Review by puehringer — APPROVED** [review]
Looks good to me! 🎉

**Pull request merged**
