### PR TITLE
Listen to copy command and copy selected rows

### PR DESCRIPTION
**Pull request by sgratzl**
**prerequisites**:

- [x] branch is up-to-date with the branch to be merged with, i.e. develop
- [x] build is successful
- [x] code is cleaned up and formatted

## Summary

add support for copying a TSV table into the clipboard upon `copy` command. If rows are selected it will only be the selected rows otherwise the whole table

### CODE REVIEW

**Comment by thinkh** [comment]
How can I test this? 

1. Open a Netlify PR demo
2. Select some rows
3. <kbd>Ctrl</kbd> + <kbd>C</kbd> 
4. Open an editor
5. <kbd>Ctrl</kbd> + <kbd>V</kbd> 

The result are not the selected rows.

**Comment by sgratzl** [comment]
when I do it:
copy paste2

ctrl-c and ctrl-v also work as expected

**Comment by thinkh** [comment]
Aha! I can confirm that it works with Chrome, but it does not work with Firefox 94 (which I used for testing). Could you please have a look if there is a way to make it compatible with Firefox?

**Comment by sgratzl** [comment]
> Aha! I can confirm that it works with Chrome, but it does not work with Firefox 94 (which I used for testing). Could you please have a look if there is a way to make it compatible with Firefox?

should be fixed. Firefox doesn't allow async manipulation of the clipboard

**Review by thinkh — APPROVED** [review]
Thanks. Now it works also in Firefox.

**Pull request merged**
